### ISSUE TITLE
Almost identical copy of compress-create-react-app

### ISSUE THREAD

**Issue by jnsjknn** [Ivan-Corporation/react-compress#1]
Hi,

I noticed you had copied my code and republished it on the npm registry.

Did you want to make something about the package better or why did you decide to do it?

**Comment by Ivan-Corporation** [comment]
Hi, i thought that you abandoned project and i had some filetypes problem when try to compress CRA
When i created it on my side and delete some filetypes (don't remember what i did really it's been winter) project suddenly begin working
But of course i'm abandoned project too... Coz literally every hosting have auto compression on their side
It's not about commerce of course but if you want i can delete it or make private (find my fixed part if you want), 
just don't want to upset you

**Comment by jnsjknn** [comment]
It's okay. The code is licensed with the MIT license anyways. I was just wondering why you did it.

**Comment by Ivan-Corporation** [comment]
I found after what it's work again:
![image](https://user-images.githubusercontent.com/58357980/176112953-da238659-f63c-4b7b-bbf1-0a8346ca4169.png)

It's seems that i deleted some filetypes for images and video/music but i don't remember how problem looked like, maybe script just don't launched with that types of files
